<a href="https://colab.research.google.com/github/DitriXNew/1C-InventoryOfObjectsByAccounts/blob/master/HW1_Dmytro_Sherstobitov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [2]:
import numpy as np
# Код оголошення векторів не можна змінювати
a = np.array([[  1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

# 1. Cума $\overline{a}$ та $\overline{b}$:

In [8]:
a + b

array([[1.5, 3. , 5. , 7. , 9. ]])

# 2. Різниця $\overline{a}$ та $\overline{b}$:

In [7]:
a - b

array([[0.5, 1. , 1. , 1. , 1. ]])

# 3. Cума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат:
Так при транспонуванні - рядки перетворюються у стовпчики (та навапаки), а складання матриць можливо тільки якщо a[i,j] = b[i,j].
В нашому випадку це не так, бо а[1,5], a b[5,1], тому, спочатку ми повинні привести їх до однієї розмірності (копіюючи рядки до кількості стовпчиків, та навпаки), що і робить numpy, по суті - CROSS JOIN.


In [9]:
a + b.T

array([[1.5, 2.5, 3.5, 4.5, 5.5],
       [2. , 3. , 4. , 5. , 6. ],
       [3. , 4. , 5. , 6. , 7. ],
       [4. , 5. , 6. , 7. , 8. ],
       [5. , 6. , 7. , 8. , 9. ]])

# 4. Матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$:

In [20]:
a @ b.T


array([[40.5]])

# 5. Матричний добуток (dot product) $\overline{a}$ та $\overline{b}$:
Для можливості розрахунку добутка - потрібно щоб кількість стовпців лівої матриці співпадала з кількістю рядків правої, тому що ми будемо перемножати кожен елемент рядка на кожен елемент стовпця, якщо вони не співадають, то нам не буде на що перемножати.

Але є декілька варіантів як знайти добуток, це залежить від задачі. Наприклад, якщо це аналітика продажу (магазин\рік) і другий магазин відкрився у березні, то можливо доповнити данні середнім продажом (орієнтовно), щоб сберегти основні властивості аналітики, або обрізати інщі магазини до розмірності, чи заповнити нулями.

In [21]:
a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

#6. Добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$:
Це поелементе множення один до одного. Можливо тільки якщо повністю співпадають розмірність матриці а і b.

In [22]:
a * b

array([[ 0.5,  2. ,  6. , 12. , 20. ]])

# 7. Ділення $\overline{a}$ та $\overline{b}$

Поелементно ділимо одну матрицю на іншу.

In [23]:
a / b

array([[2.        , 2.        , 1.5       , 1.33333333, 1.25      ]])

# 8. Ділення $\overline{a}$ та $\overline{b}^T$

Так як є хоч одна матриця з одиничною розмірністю, то нампі зробив бродкаст - привів кількість стовпців в b до кількості рядков в а, а потім розділив.

In [24]:
a / b.T

array([[ 2.        ,  4.        ,  6.        ,  8.        , 10.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 0.5       ,  1.        ,  1.5       ,  2.        ,  2.5       ],
       [ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ,  1.25      ]])

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

#### 2.1 Зменши вектор  $x$  в 2 рази по вісі  OX  та збільш в 3 рази по вісі  OY .

$$
M_1 =
\left (\begin{array}{cc}
0.5 & 0\\
0 & 3\\
\end{array}\right)
$$

$$
M_1x =
\left(\begin{array}{cc}
0.5 & 0\\
0 & 3
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
0.5 \cdot 2 + 0 \cdot 1\\
0 \cdot 2 + 3 \cdot 1
\end{array}\right)=
\left(\begin{array}{cc}
1\\
3
\end{array}\right)
$$

#### 2.2 Відобрази вектор $x$ відносно початку координат.

$$
M_2 = \left (\begin{array}{cc}
-1 & 0\\
0 & -1\\
\end{array}\right)
$$

$$
M_2x =
\left(\begin{array}{cc}
-1 & 0\\
0 & -1\\
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
-1 \cdot 2 + 0 \cdot 1\\
0 \cdot 2 + -1 \cdot 1
\end{array}\right)=
\left(\begin{array}{cc}
-2\\
-1
\end{array}\right)
$$

#### 2.3 Перенеси вектор $x$, задавши відповідну матрицю і помноживши на неї,  на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 = \left (\begin{array}{cc}
-3\\
1\\
\end{array}\right)
\\
M_3x = \left (\begin{array}{cc}
-3\\
1\\
\end{array}\right)+\left (\begin{array}{cc}
2\\
1\\
\end{array}\right)=\left (\begin{array}{cc}
-1\\
2\\
\end{array}\right)
$$
Через множення:
$$
M_3 = \left (\begin{array}{cc}
1 & 0 & -3\\
0 & 1 & 1\\
0&0&1
\end{array}\right)
\\
M_3x = \left (\begin{array}{cc}
1 & 0 & -3\\
0 & 1 & 1\\
0&0&1
\end{array}\right)*\left (\begin{array}{cc}
2\\
1\\
1
\end{array}\right)=\left (\begin{array}{cc}
-1\\
2\\
1
\end{array}\right)
$$

так як декартові координати однорідні (тому що в задачі сказано зробити сдвиг через матрицю множення), то останню координату ділимо на інші і відкидуємо, тому отримаємо:
$$
\left (\begin{array}{cc}
-1\\
2\\
\end{array}\right)
$$

#### 2.4 Змісти(shear) вектор $x$ на 60° по вісі $OY$.


$$
M_4 = \left(\begin{array}{cc}
1 & 0\\
tan(60^o) & 1\\
\end{array}\right)
\\
M_4x = \left(\begin{array}{cc}
1 & 0\\
tan(60^o) & 1\\
\end{array}\right)*\left(\begin{array}{cc}
2\\
1
\end{array}\right)=\left(\begin{array}{cc}
2\\
2\sqrt{3} + 1 = 4.4
\end{array}\right)
$$

#### 2.5 Поверни вектор $x$ на 30°.

$$
M_5 = \left(\begin{array}{cc}
cos(30^o) & -sin(30^o)\\
sin(30^o) & cos(30^o)\\
\end{array}\right)
\\
M_5x = \left(\begin{array}{cc}
0.8 & -0.5\\
0.5 & 0.8\\
\end{array}\right)*\left(\begin{array}{cc}
2\\
1
\end{array}\right)=\left(\begin{array}{cc}
1.1\\
1.8
\end{array}\right)
$$

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

$$
M_6 = M_5 \cdot M_4 \cdot M_2 \cdot M_1 = \left(\begin{array}{cc}
cos(30^o) & -sin(30^o)\\
sin(30^o) & cos(30^o)\\
\end{array}\right)*\left(\begin{array}{cc}
1 & 0\\
tan(60^o) & 1\\
\end{array}\right)*\left (\begin{array}{cc}
-1 & 0\\
0 & -1\\
\end{array}\right)*\left (\begin{array}{cc}
0.5 & 0\\
0 & 3\\
\end{array}\right)
$$

$$
M_6 =
\left (\begin{array}{cc}
? & ?\\
? & ?
\end{array}\right)
\\
M_6x = ?
$$

# Завдання 2 (Альтернативне)

In [ ]:
import cv2 as cv
import urllib
import numpy as np
from google.colab.patches import cv2_imshow as cv_imshow

# Read an image
def read_image_by_url(url):
    req = urllib.request.urlopen(url)
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
    img = cv.imdecode(arr, -1)
    return img

url = ''

img = read_image_by_url(url)

In [ ]:
cv_imshow(img)